///|
pub extend Statements with @moonbitlang/core/debug.Debug::{to_repr}

///|
pub extend Statement with @moonbitlang/core/debug.Debug::{to_repr}

///|
pub extend QueryStmt with @moonbitlang/core/debug.Debug::{to_repr}

///|
pub extend SetExpr with @moonbitlang/core/debug.Debug::{to_repr}

///|
pub extend SelectStmt with @moonbitlang/core/debug.Debug::{to_repr}

///|
pub extend SetOperator with @moonbitlang/core/debug.Debug::{to_repr}

///|
pub extend Projection with @moonbitlang/core/debug.Debug::{to_repr}

///|
pub extend Expr with @moonbitlang/core/debug.Debug::{to_repr}

///|
pub extend Literal with @moonbitlang/core/debug.Debug::{to_repr}

///|
pub extend ArrayExpr with @moonbitlang/core/debug.Debug::{to_repr}

///|
pub extend AccessExpr with @moonbitlang/core/debug.Debug::{to_repr}

///|
pub extend Subscript with @moonbitlang/core/debug.Debug::{to_repr}

///|
pub extend Cte with @moonbitlang/core/debug.Debug::{to_repr}

///|
pub extend BinaryOperator with @moonbitlang/core/debug.Debug::{to_repr}

///|
pub extend UnaryOperator with @moonbitlang/core/debug.Debug::{to_repr}

///|
pub extend OrderByExpr with @moonbitlang/core/debug.Debug::{to_repr}

///|
pub extend TableRef with @moonbitlang/core/debug.Debug::{to_repr}

///|
pub extend TableFactor with @moonbitlang/core/debug.Debug::{to_repr}

///|
pub extend TableAlias with @moonbitlang/core/debug.Debug::{to_repr}

///|
pub extend Join with @moonbitlang/core/debug.Debug::{to_repr}

///|
pub extend JoinOperator with @moonbitlang/core/debug.Debug::{to_repr}

///|
pub extend JoinConstraint with @moonbitlang/core/debug.Debug::{to_repr}

///|
pub extend IntervalQualifier with @moonbitlang/core/debug.Debug::{to_repr}

///|
pub extend PrimaryDatetimeField with @moonbitlang/core/debug.Debug::{to_repr}

///|
pub extend DatetimeUnit with @moonbitlang/core/debug.Debug::{to_repr}

///|
pub extend CaseExpr with @moonbitlang/core/debug.Debug::{to_repr}

///|
pub extend WindowSpec with @moonbitlang/core/debug.Debug::{to_repr}

///|
pub extend WindowFrameClause with @moonbitlang/core/debug.Debug::{to_repr}

///|
pub extend WindowFrameUnits with @moonbitlang/core/debug.Debug::{to_repr}

///|
pub extend WindowFrameBound with @moonbitlang/core/debug.Debug::{to_repr}

///|
pub extend CreateTableStmt with @moonbitlang/core/debug.Debug::{to_repr}

///|
pub extend CreateTableDefinition with @moonbitlang/core/debug.Debug::{to_repr}

///|
pub extend ColumnDef with @moonbitlang/core/debug.Debug::{to_repr}

///|
pub extend DataType with @moonbitlang/core/debug.Debug::{to_repr}

///|
pub extend ColumnDefOption with @moonbitlang/core/debug.Debug::{to_repr}

///|
pub extend CreateViewStmt with @moonbitlang/core/debug.Debug::{to_repr}

///|
pub extend ViewColumnDef with @moonbitlang/core/debug.Debug::{to_repr}

///|
pub extend CreateIndexStmt with @moonbitlang/core/debug.Debug::{to_repr}

///|
pub extend IndexMethod with @moonbitlang/core/debug.Debug::{to_repr}

///|
pub extend IndexColumn with @moonbitlang/core/debug.Debug::{to_repr}

///|
pub extend CreateDatabaseStmt with @moonbitlang/core/debug.Debug::{to_repr}

///|
pub extend CreateSchemaStmt with @moonbitlang/core/debug.Debug::{to_repr}

///|
pub extend CreateFunctionStmt with @moonbitlang/core/debug.Debug::{to_repr}

///|
pub extend FunctionParameter with @moonbitlang/core/debug.Debug::{to_repr}

///|
pub extend ParameterMode with @moonbitlang/core/debug.Debug::{to_repr}

///|
pub extend CreateProcedureStmt with @moonbitlang/core/debug.Debug::{to_repr}

///|
pub extend CreateSequenceStmt with @moonbitlang/core/debug.Debug::{to_repr}

///|
pub extend SequenceLimit with @moonbitlang/core/debug.Debug::{to_repr}

///|
pub extend SequenceOwnedBy with @moonbitlang/core/debug.Debug::{to_repr}

///|
pub extend DropViewStmt with @moonbitlang/core/debug.Debug::{to_repr}

///|
pub extend DuplicateTreatment with @moonbitlang/core/debug.Debug::{to_repr}

///|
pub extend TableConstraint with @moonbitlang/core/debug.Debug::{to_repr}

///|
pub extend ObjectName with @moonbitlang/core/debug.Debug::{to_repr}

///|
pub extend Top with @moonbitlang/core/debug.Debug::{to_repr}

///|
pub extend InsertStmt with @moonbitlang/core/debug.Debug::{to_repr}

///|
pub extend InsertSource with @moonbitlang/core/debug.Debug::{to_repr}

///|
pub extend DeleteStmt with @moonbitlang/core/debug.Debug::{to_repr}

///|
pub extend UpdateStmt with @moonbitlang/core/debug.Debug::{to_repr}

///|
pub extend Assignment with @moonbitlang/core/debug.Debug::{to_repr}

///|
pub extend MergeStmt with @moonbitlang/core/debug.Debug::{to_repr}

///|
pub extend MergeSource with @moonbitlang/core/debug.Debug::{to_repr}

///|
pub extend MergeWhenClause with @moonbitlang/core/debug.Debug::{to_repr}

///|
pub extend MergeMatchType with @moonbitlang/core/debug.Debug::{to_repr}

///|
pub extend MergeAction with @moonbitlang/core/debug.Debug::{to_repr}

///|
pub extend TruncateStmt with @moonbitlang/core/debug.Debug::{to_repr}

///|
pub extend DropTableStmt with @moonbitlang/core/debug.Debug::{to_repr}

///|
pub extend DropIndexStmt with @moonbitlang/core/debug.Debug::{to_repr}

///|
pub extend AlterTableStmt with @moonbitlang/core/debug.Debug::{to_repr}

///|
pub extend AlterTableOperation with @moonbitlang/core/debug.Debug::{to_repr}

///|
pub extend AlterIndexStmt with @moonbitlang/core/debug.Debug::{to_repr}

///|
pub extend AlterIndexOperation with @moonbitlang/core/debug.Debug::{to_repr}

///|
pub extend IndexParameter with @moonbitlang/core/debug.Debug::{to_repr}

///|
pub extend ShowStmt with @moonbitlang/core/debug.Debug::{to_repr}

///|
pub extend ShowType with @moonbitlang/core/debug.Debug::{to_repr}

///|
pub extend ShowFilter with @moonbitlang/core/debug.Debug::{to_repr}

///|
pub extend SetStmt with @moonbitlang/core/debug.Debug::{to_repr}

///|
pub extend SetScope with @moonbitlang/core/debug.Debug::{to_repr}

///|
pub extend SetAssignment with @moonbitlang/core/debug.Debug::{to_repr}

///|
pub extend UseStmt with @moonbitlang/core/debug.Debug::{to_repr}

///|
pub extend CopyStmt with @moonbitlang/core/debug.Debug::{to_repr}

///|
pub extend CopySource with @moonbitlang/core/debug.Debug::{to_repr}

///|
pub extend CopyDirection with @moonbitlang/core/debug.Debug::{to_repr}

///|
pub extend CopyTarget with @moonbitlang/core/debug.Debug::{to_repr}

///|
pub extend CopyOption with @moonbitlang/core/debug.Debug::{to_repr}

///|
pub extend CopyFormat with @moonbitlang/core/debug.Debug::{to_repr}

///|
pub extend CopyForceQuote with @moonbitlang/core/debug.Debug::{to_repr}

///|
pub extend OnInsert with @moonbitlang/core/debug.Debug::{to_repr}

///|
pub extend OnConflictClause with @moonbitlang/core/debug.Debug::{to_repr}

///|
pub extend ConflictTarget with @moonbitlang/core/debug.Debug::{to_repr}

///|
pub extend ConflictAction with @moonbitlang/core/debug.Debug::{to_repr}

///|
pub extend SqliteOnConflict with @moonbitlang/core/debug.Debug::{to_repr}

///|
pub extend BeginStmt with @moonbitlang/core/debug.Debug::{to_repr}

///|
pub extend CommitStmt with @moonbitlang/core/debug.Debug::{to_repr}

///|
pub extend RollbackStmt with @moonbitlang/core/debug.Debug::{to_repr}

///|
pub extend SavepointStmt with @moonbitlang/core/debug.Debug::{to_repr}

///|
pub extend ReleaseSavepointStmt with @moonbitlang/core/debug.Debug::{to_repr}

///|
pub extend GrantStmt with @moonbitlang/core/debug.Debug::{to_repr}

///|
pub extend Privilege with @moonbitlang/core/debug.Debug::{to_repr}

///|
pub extend RevokeStmt with @moonbitlang/core/debug.Debug::{to_repr}

///|
pub extend RevokeOption with @moonbitlang/core/debug.Debug::{to_repr}

///|
pub extend LoadDataStmt with @moonbitlang/core/debug.Debug::{to_repr}

///|
pub extend LoadDataDuplicateHandling with @moonbitlang/core/debug.Debug::{
  to_repr,
}

///|
pub extend LoadDataFieldsOptions with @moonbitlang/core/debug.Debug::{to_repr}

///|
pub extend LoadDataLinesOptions with @moonbitlang/core/debug.Debug::{to_repr}

///|
pub extend PrepareStmt with @moonbitlang/core/debug.Debug::{to_repr}

///|
pub extend ExecuteStmt with @moonbitlang/core/debug.Debug::{to_repr}

///|
pub extend DeallocateStmt with @moonbitlang/core/debug.Debug::{to_repr}

///|
pub extend SqlParserError with @moonbitlang/core/debug.Debug::{to_repr}

///|
pub extend Keyword with @moonbitlang/core/debug.Debug::{to_repr}

///|
pub extend LexerError with @moonbitlang/core/debug.Debug::{to_repr}

///|
pub extend Token with @moonbitlang/core/debug.Debug::{to_repr}

///|
pub extend ParserError with @moonbitlang/core/debug.Debug::{to_repr}
