///|
pub extend ANSI with Dialect::{
  supports_filter_during_aggregation,
  parse_statement,
  supports_within_after_array_aggregation,
  requires_column_types_in_create_table,
  supports_boolean_literals,
  supports_string_literal_backslash_escape,
  supports_array_syntax,
  supports_double_quoted_identifiers,
  parse_expr,
  supports_named_parameters,
  supports_if_not_exists,
  read_keyword,
}

///|
pub extend BigQuery with Dialect::{
  supports_filter_during_aggregation,
  parse_statement,
  supports_within_after_array_aggregation,
  requires_column_types_in_create_table,
  supports_boolean_literals,
  supports_string_literal_backslash_escape,
  supports_array_syntax,
  supports_double_quoted_identifiers,
  parse_expr,
  supports_named_parameters,
  supports_if_not_exists,
  read_keyword,
}

///|
pub extend ClickHouse with Dialect::{
  supports_filter_during_aggregation,
  parse_statement,
  supports_within_after_array_aggregation,
  requires_column_types_in_create_table,
  supports_boolean_literals,
  supports_string_literal_backslash_escape,
  supports_array_syntax,
  supports_double_quoted_identifiers,
  parse_expr,
  supports_named_parameters,
  supports_if_not_exists,
  read_keyword,
}

///|
pub extend DuckDB with Dialect::{
  supports_filter_during_aggregation,
  parse_statement,
  supports_within_after_array_aggregation,
  requires_column_types_in_create_table,
  supports_boolean_literals,
  supports_string_literal_backslash_escape,
  supports_array_syntax,
  supports_double_quoted_identifiers,
  parse_expr,
  supports_named_parameters,
  supports_if_not_exists,
  read_keyword,
}

///|
pub extend Generic with Dialect::{
  supports_filter_during_aggregation,
  parse_statement,
  supports_within_after_array_aggregation,
  requires_column_types_in_create_table,
  supports_boolean_literals,
  supports_string_literal_backslash_escape,
  supports_array_syntax,
  supports_double_quoted_identifiers,
  parse_expr,
  supports_named_parameters,
  supports_if_not_exists,
  read_keyword,
}

///|
pub extend MySQL with Dialect::{
  supports_filter_during_aggregation,
  parse_statement,
  supports_within_after_array_aggregation,
  requires_column_types_in_create_table,
  supports_boolean_literals,
  supports_string_literal_backslash_escape,
  supports_array_syntax,
  supports_double_quoted_identifiers,
  parse_expr,
  supports_named_parameters,
  supports_if_not_exists,
  read_keyword,
}

///|
pub extend Postgres with Dialect::{
  supports_filter_during_aggregation,
  parse_statement,
  supports_within_after_array_aggregation,
  requires_column_types_in_create_table,
  supports_boolean_literals,
  supports_string_literal_backslash_escape,
  supports_array_syntax,
  supports_double_quoted_identifiers,
  parse_expr,
  supports_named_parameters,
  supports_if_not_exists,
  read_keyword,
}

///|
pub extend Redshift with Dialect::{
  supports_filter_during_aggregation,
  parse_statement,
  supports_within_after_array_aggregation,
  requires_column_types_in_create_table,
  supports_boolean_literals,
  supports_string_literal_backslash_escape,
  supports_array_syntax,
  supports_double_quoted_identifiers,
  parse_expr,
  supports_named_parameters,
  supports_if_not_exists,
  read_keyword,
}

///|
pub extend Snowflake with Dialect::{
  supports_filter_during_aggregation,
  parse_statement,
  supports_within_after_array_aggregation,
  requires_column_types_in_create_table,
  supports_boolean_literals,
  supports_string_literal_backslash_escape,
  supports_array_syntax,
  supports_double_quoted_identifiers,
  parse_expr,
  supports_named_parameters,
  supports_if_not_exists,
  read_keyword,
}

///|
pub extend SQLite with Dialect::{
  supports_filter_during_aggregation,
  parse_statement,
  supports_within_after_array_aggregation,
  requires_column_types_in_create_table,
  supports_boolean_literals,
  supports_string_literal_backslash_escape,
  supports_array_syntax,
  supports_double_quoted_identifiers,
  parse_expr,
  supports_named_parameters,
  supports_if_not_exists,
  read_keyword,
}
